name: BattleShip
version: 0.1.0.0
github: "yourusername/battleship"
license: MIT
author: "Your Name"
maintainer: "your.email@example.com"
copyright: "2025 Your Name"

# Only include files that ACTUALLY EXIST
extra-source-files:
  - README.md
  - CHANGELOG.md

description: |
  Multiplayer Battleship game with Haskell backend.

dependencies:
  base: ">= 4.7 && < 5"
  scotty: "*"
  wai-middleware-static: "*"
  aeson: "*"
  text: "*"
  http-types: "*"
  stm: "*"
  "parallel": ">= 3.2.2.0"


ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Game.Types



executables:
  battleship-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - BattleShip

tests:
  battleship-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - BattleShip
      - hspec >= 2.10
      - QuickCheck >= 2.14
      - hspec-discover >= 2.10
