resolver: lts-22.9  # GHC 9.6.4

packages:
- .

extra-deps: []

system-ghc: false
allow-newer: false

flags: {}

extra-package-dbs: []

ghc-options:
  "$everything": -O2 -Wall

build:
  haddock: false
  keep-going: true
