# Stack version
resolver: lts-22.28  # GHC 9.6.6

# Packages
packages:
- .

# Extra dependencies (if needed)
extra-deps: []

# Build flags
flags: {}

# GHC options
ghc-options:
  "$everything": -O0 -j4  # Fast build, use 4 cores

# Allow newer versions
allow-newer: true
